// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyExternalCapability(arg1:main.ApplyExternalCapabilityRequest):Promise<main.ApplyExternalCapabilityResult>;

export function ApplyFingerprintImport(arg1:main.FingerprintImportApplyRequest):Promise<main.FingerprintImportApplyResult>;

export function ApplyTemplateCategories(arg1:main.ApplyCategoriesRequest):Promise<main.ApplyCategoriesResult>;

export function ApplyYamlCollection(arg1:main.ApplyCategoriesRequest):Promise<main.ApplyCategoriesResult>;

export function AuditFingerprintKnowledge(arg1:string):Promise<main.FingerprintAuditResult>;

export function AutoFixNucleiTemplates(arg1:string,arg2:main.AutoFixOptions):Promise<main.AutoFixResult>;

export function CancelCurrentTask():Promise<string>;

export function ClassifyDDDDBuiltinPocs(arg1:string):Promise<main.FingerprintPocCatalogResult>;

export function ClassifyExternalPocsByDDDD(arg1:string,arg2:string):Promise<main.FingerprintPocCatalogResult>;

export function ConvertMarkdownBatch(arg1:Array<main.ConvertBatchItem>):Promise<main.ConvertBatchResult>;

export function ConvertMarkdownFile(arg1:string):Promise<main.ConvertResult>;

export function ConvertMarkdownFolder(arg1:string):Promise<main.ConvertedBatch>;

export function ConvertMarkdownText(arg1:string,arg2:string):Promise<main.ConvertResult>;

export function DeletePath(arg1:string):Promise<void>;

export function ExtractBaseNames(arg1:string):Promise<Array<string>>;

export function LoadDirectory(arg1:string,arg2:boolean):Promise<main.LoadDirectoryResult>;

export function LoadFile(arg1:string):Promise<main.YamlFile>;

export function LoadMarkdownDirectory(arg1:string):Promise<main.LoadDirectoryResult>;

export function MoveTemplateDuplicates(arg1:main.MoveDuplicatesRequest):Promise<main.MoveDuplicatesResult>;

export function OpenWithDefaultApp(arg1:string):Promise<void>;

export function PreviewFingerprintImport(arg1:string,arg2:string):Promise<main.FingerprintImportPreviewResult>;

export function PreviewDirImport(arg1:string,arg2:string):Promise<main.DirImportPreviewResult>;

export function RevealInFileManager(arg1:string):Promise<void>;

export function RestoreExternalCapabilityBackup(arg1:main.RestoreExternalCapabilityBackupRequest):Promise<main.RestoreExternalCapabilityBackupResult>;

export function SaveExternalDirReview(arg1:main.SaveExternalDirReviewRequest):Promise<main.SavedReviewResult>;

export function SaveExternalFingerprintReview(arg1:main.SaveExternalFingerprintReviewRequest):Promise<main.SavedReviewResult>;

export function SaveExternalPocReview(arg1:main.SaveExternalPocReviewRequest):Promise<main.SavedReviewResult>;

export function SaveSourceFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SaveYamlBatch(arg1:string,arg2:Array<main.YamlOutFile>):Promise<main.SaveYamlBatchResult>;

export function ScanDuplicateTemplates(arg1:string):Promise<main.DupScanResult>;

export function ScanExternalCapability(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.ExternalCapabilityScanResult>;

export function ScanTemplateCategories(arg1:string):Promise<main.CategoryScanResult>;

export function ScanYamlCollection(arg1:string):Promise<main.CollectScanResult>;

export function SelectDirectory():Promise<string>;

export function SelectFile():Promise<string>;

export function SendBufferToFolder(arg1:string,arg2:Array<main.YamlFile>):Promise<number>;

export function ValidateNucleiTemplates(arg1:string):Promise<main.NucleiValidateResult>;
