// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyExternalCapability(arg1) {
  return window['go']['main']['App']['ApplyExternalCapability'](arg1);
}

export function ApplyFingerprintImport(arg1) {
  return window['go']['main']['App']['ApplyFingerprintImport'](arg1);
}

export function ApplyTemplateCategories(arg1) {
  return window['go']['main']['App']['ApplyTemplateCategories'](arg1);
}

export function ApplyYamlCollection(arg1) {
  return window['go']['main']['App']['ApplyYamlCollection'](arg1);
}

export function AuditFingerprintKnowledge(arg1) {
  return window['go']['main']['App']['AuditFingerprintKnowledge'](arg1);
}

export function AutoFixNucleiTemplates(arg1, arg2) {
  return window['go']['main']['App']['AutoFixNucleiTemplates'](arg1, arg2);
}

export function CancelCurrentTask() {
  return window['go']['main']['App']['CancelCurrentTask']();
}

export function ClassifyDDDDBuiltinPocs(arg1) {
  return window['go']['main']['App']['ClassifyDDDDBuiltinPocs'](arg1);
}

export function ClassifyExternalPocsByDDDD(arg1, arg2) {
  return window['go']['main']['App']['ClassifyExternalPocsByDDDD'](arg1, arg2);
}

export function ConvertMarkdownBatch(arg1) {
  return window['go']['main']['App']['ConvertMarkdownBatch'](arg1);
}

export function ConvertMarkdownFile(arg1) {
  return window['go']['main']['App']['ConvertMarkdownFile'](arg1);
}

export function ConvertMarkdownFolder(arg1) {
  return window['go']['main']['App']['ConvertMarkdownFolder'](arg1);
}

export function ConvertMarkdownText(arg1, arg2) {
  return window['go']['main']['App']['ConvertMarkdownText'](arg1, arg2);
}

export function DeletePath(arg1) {
  return window['go']['main']['App']['DeletePath'](arg1);
}

export function ExtractBaseNames(arg1) {
  return window['go']['main']['App']['ExtractBaseNames'](arg1);
}

export function LoadDirectory(arg1, arg2) {
  return window['go']['main']['App']['LoadDirectory'](arg1, arg2);
}

export function LoadFile(arg1) {
  return window['go']['main']['App']['LoadFile'](arg1);
}

export function LoadMarkdownDirectory(arg1) {
  return window['go']['main']['App']['LoadMarkdownDirectory'](arg1);
}

export function MoveTemplateDuplicates(arg1) {
  return window['go']['main']['App']['MoveTemplateDuplicates'](arg1);
}

export function OpenWithDefaultApp(arg1) {
  return window['go']['main']['App']['OpenWithDefaultApp'](arg1);
}

export function PreviewFingerprintImport(arg1, arg2) {
  return window['go']['main']['App']['PreviewFingerprintImport'](arg1, arg2);
}

export function PreviewDirImport(arg1, arg2) {
  return window['go']['main']['App']['PreviewDirImport'](arg1, arg2);
}

export function RevealInFileManager(arg1) {
  return window['go']['main']['App']['RevealInFileManager'](arg1);
}

export function RestoreExternalCapabilityBackup(arg1) {
  return window['go']['main']['App']['RestoreExternalCapabilityBackup'](arg1);
}

export function SaveExternalFingerprintReview(arg1) {
  return window['go']['main']['App']['SaveExternalFingerprintReview'](arg1);
}

export function SaveExternalDirReview(arg1) {
  return window['go']['main']['App']['SaveExternalDirReview'](arg1);
}

export function SaveExternalPocReview(arg1) {
  return window['go']['main']['App']['SaveExternalPocReview'](arg1);
}

export function SaveSourceFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveSourceFile'](arg1, arg2, arg3);
}

export function SaveYamlBatch(arg1, arg2) {
  return window['go']['main']['App']['SaveYamlBatch'](arg1, arg2);
}

export function ScanDuplicateTemplates(arg1) {
  return window['go']['main']['App']['ScanDuplicateTemplates'](arg1);
}

export function ScanExternalCapability(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ScanExternalCapability'](arg1, arg2, arg3, arg4);
}

export function ScanTemplateCategories(arg1) {
  return window['go']['main']['App']['ScanTemplateCategories'](arg1);
}

export function ScanYamlCollection(arg1) {
  return window['go']['main']['App']['ScanYamlCollection'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SendBufferToFolder(arg1, arg2) {
  return window['go']['main']['App']['SendBufferToFolder'](arg1, arg2);
}

export function ValidateNucleiTemplates(arg1) {
  return window['go']['main']['App']['ValidateNucleiTemplates'](arg1);
}
